#!/usr/bin/perl

# int2ip.pl	ccosby	0.1	31-Jan-2002
# Convert an integer as found in dncsdb into a dotted quad IP address.
#
use Socket;
use strict;

my $VERSION = 0.1;
my $DATE = "31-Jan-2002";

# need to pass at least 1 ip address in
usage() if $#ARGV < 0;

my $i = 0;				# only needed for the old version of perl on DNCS (5.003)
for ( $i=0; $i<=$#ARGV; $i++ ) {	# only needed for the old version of perl on DNCS (5.003)
#foreach my $ipInt (@ARGV) {		# works with any recent perl
	my $ipInt = $ARGV[$i];
	my $ip = inet_ntoa(pack('N', $ipInt));
	printf("%d   %s\n", $ipInt, $ip);
}

exit 0;


sub usage {
	print <<EOF;
int2ip.pl version $VERSION [$DATE] (Perl $])

Usage: int2ip.pl ip1 [ip2 ip3 ip4 ...]

EOF
	exit 1;
}
